/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:599795:
  appc.background(230);
} //_CODE_:window1:599795:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:variable_slide:698200:

} //_CODE_:variable_slide:698200:

public void dropList1_click(GDropList source, GEvent event) { //_CODE_:variable_adjuster:515417:
  setting = variable_adjuster.getSelectedText();  
  for (Animal a : animals) {
    if (setting.equals("Aggression")) {
      variable_slide.setLimits(a.aggression, 1, 10);
    } else if (setting.equals("Size")) {
      variable_slide.setLimits(a.size, 3, 12);
    } else if (setting.equals("Speed")) {
      variable_slide.setLimits(a.speed, 15, 5);
    }
  }
} //_CODE_:variable_adjuster:515417:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  variable_slide = new GCustomSlider(window1, 114, 32, 100, 40, "grey_blue");
  variable_slide.setLimits(0.5, 0.0, 1.0);
  variable_slide.setNumberFormat(G4P.DECIMAL, 2);
  variable_slide.setOpaque(false);
  variable_slide.addEventHandler(this, "custom_slider1_change1");
  variable_adjuster = new GDropList(window1, 10, 21, 90, 80, 3, 10);
  variable_adjuster.setItems(loadStrings("list_515417"), 0);
  variable_adjuster.addEventHandler(this, "dropList1_click");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider variable_slide; 
GDropList variable_adjuster; 
